### ISSUE TITLE
Uncaught TypeError: setTimeout(...).unref is not a function

### ISSUE THREAD

**Issue by Ollo** [siddharthkp/atom-import-cost#16]
[Enter steps to reproduce:]

1. Open Editor

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-import-cost](https://github.com/siddharthkp/atom-import-cost) package 1.2.0

### Stack Trace

Uncaught TypeError: setTimeout(...).unref is not a function

```
At /Users/ray/.atom/packages/atom-import-cost/node_modules/worker-farm/lib/farm.js:135

TypeError: setTimeout(...).unref is not a function
    at Farm.stopChild (/packages/atom-import-cost/node_modules/worker-farm/lib/farm.js:135:37)
    at /packages/atom-import-cost/node_modules/worker-farm/lib/farm.js:96:10)
```
### Non-Core Packages

```
accents-ui 1.3.0 
atom-dark-fusion-syntax 2.2.1 
atom-import-cost 1.2.0 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
base-16-ocean-dark-ui-theme 1.7.2 
busy-signal 1.4.3 
chameleon-ui 2.0.0 
chester-atom-syntax 0.3.2 
danikai-light-syntax 0.6.1 
dark-flat-ui 1.2.4 
daylight-ui 0.2.2 
docblockr 0.13.7 
duotone-light-syntax 2.1.0 
earthsung-by-jackson-syntax 0.3.0 
editorconfig 2.2.2 
file-icons 2.1.21 
firewatch-green-syntax 1.1.0 
import-cost-atom 1.0.8 
intentions 1.1.5 
jsonlint 1.1.4 
kimbie-light 2.0.2 
language-elixir 0.22.0 
language-jade 0.7.3 
language-javascript-jsx 0.3.7 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
min-ui 0.0.4 
no-caffeine-syntax 0.21.0 
octocat-syntax 2.2.2 
pinned-tabs 2.0.6 
react 0.18.0 
sepia-light-ui 0.5.0 
sepia-syntax 1.1.0 
slime 2.4.0 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
teletype 0.13.3 
termination 0.6.2 
unicorn-light-syntax 3.1.0 
wordcount 3.0.0 
```

**Comment by Ollo** [comment]
Plugin audit and updates have cleared this issue up.

**Comment by erwstout** [comment]
@Ollo can you elaborate on the audit part? I'm all up to date and I'm also getting this error non-stop.

**Comment by Ollo** [comment]
@erwstout I removed several of the plugins and themes that I hadn't used in a while and it worked sporadically. At this point I have removed this plugin too as the error was interrupting too frequently :(

**Comment by erwstout** [comment]
Thanks Joshua - I think I'll just remove it too for the time being.
