### ISSUE TITLE
Unexpected reserved word 'package'

### ISSUE THREAD

**Issue by SilentGlasses** [siddharthkp/atom-import-cost#19]
### Prerequisites

Not able to perform the following as Atom is dead and Pulsar took over. The links go to the defunct Atom site which no longer has any information. Let me know what alternative methods to use.

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Pulsar package that provides the described functionality: <https://atom.io/packages>

### Description

Plugin not working, spits out below error right after install.

### Steps to Reproduce

1. install plugin
2. Error message pops up

**Expected behavior:**

Plugin to work as designed.

**Actual behavior:**

Plugin throws error right after install

### Versions

**Pulsar**: 1.108.2023090103 x64
**Electron**: 12.2.3
**OS**: Pop!_OS 22.04
**Thrown From**: [atom-import-cost](https://github.com/siddharthkp/atom-import-cost) package 1.2.0

### Stack Trace

Failed to load the atom-import-cost package

```
At /home/framirez/.pulsar/packages/atom-import-cost/lib/main.js: Unexpected reserved word 'package'. (57:29)

  55 |
  56 |     emitter.on('start', packages => this.handleCalculatingStart(packages))
> 57 |     emitter.on('calculated', package => this.handleCalculatedPackage(package))
     |                              ^
  58 |     emitter.on('done', () => this.handleCalculationDone())
  59 |   },
  60 |

SyntaxError: /home/framirez/.pulsar/packages/atom-import-cost/lib/main.js: Unexpected reserved word 'package'. (57:29)

  55 |
  56 |     emitter.on('start', packages => this.handleCalculatingStart(packages))
> 57 |     emitter.on('calculated', package => this.handleCalculatedPackage(package))
     |                              ^
  58 |     emitter.on('done', () => this.handleCalculationDone())
  59 |   },
  60 |
    at instantiate (/app.asar/node_modules/@babel/parser/lib/index.js:67:32)
    at constructor (/app.asar/node_modules/@babel/parser/lib/index.js:364:12)
    at FlowParserMixin.raise (/app.asar/node_modules/@babel/parser/lib/index.js:3364:19)
    at FlowParserMixin.checkReservedWord (/app.asar/node_modules/@babel/parser/lib/index.js:12464:12)
    at FlowParserMixin.parseIdentifierName (/app.asar/node_modules/@babel/parser/lib/index.js:12412:12)
    at FlowParserMixin.parseIdentifier (/app.asar/node_modules/@babel/parser/lib/index.js:12387:23)
    at FlowParserMixin.parseExprAtom (/app.asar/node_modules/@babel/parser/lib/index.js:11542:27)
    at FlowParserMixin.parseExprAtom (/app.asar/node_modules/@babel/parser/lib/index.js:7238:20)
    at FlowParserMixin.parseExprSubscripts (/app.asar/node_modules/@babel/parser/lib/index.js:11171:23)
    at FlowParserMixin.parseUpdate (/app.asar/node_modules/@babel/parser/lib/index.js:11153:21)
    at FlowParserMixin.parseMaybeUnary (/app.asar/node_modules/@babel/parser/lib/index.js:11127:23)
    at FlowParserMixin.parseMaybeUnaryOrPrivate (/app.asar/node_modules/@babel/parser/lib/index.js:10956:61)
    at FlowParserMixin.parseExprOps (/app.asar/node_modules/@babel/parser/lib/index.js:10962:23)
    at FlowParserMixin.parseMaybeConditional (/app.asar/node_modules/@babel/parser/lib/index.js:10937:23)
    at FlowParserMixin.parseMaybeAssign (/app.asar/node_modules/@babel/parser/lib/index.js:10895:21)
    at FlowParserMixin.parseMaybeAssign (/app.asar/node_modules/@babel/parser/lib/index.js:6030:18)
    at /app.asar/node_modules/@babel/parser/lib/index.js:10863:39
    at FlowParserMixin.allowInAnd (/app.asar/node_modules/@babel/parser/lib/index.js:12640:12)
    at FlowParserMixin.parseMaybeAssignAllowIn (/app.asar/node_modules/@babel/parser/lib/index.js:10863:17)
    at FlowParserMixin.parseExprListItem (/app.asar/node_modules/@babel/parser/lib/index.js:12380:18)
    at FlowParserMixin.parseCallExpressionArguments (/app.asar/node_modules/@babel/parser/lib/index.js:11367:22)
    at FlowParserMixin.parseCoverCallAndAsyncArrowHead (/app.asar/node_modules/@babel/parser/lib/index.js:11279:29)
    at FlowParserMixin.parseSubscript (/app.asar/node_modules/@babel/parser/lib/index.js:11210:19)
    at FlowParserMixin.parseSubscript (/app.asar/node_modules/@babel/parser/lib/index.js:6139:18)
    at FlowParserMixin.parseSubscripts (/app.asar/node_modules/@babel/parser/lib/index.js:11184:19)
    at FlowParserMixin.parseSubscripts (/app.asar/node_modules/@babel/parser/lib/index.js:6105:18)
    at FlowParserMixin.parseExprSubscripts (/app.asar/node_modules/@babel/parser/lib/index.js:11175:17)
    at FlowParserMixin.parseUpdate (/app.asar/node_modules/@babel/parser/lib/index.js:11153:21)
    at FlowParserMixin.parseMaybeUnary (/app.asar/node_modules/@babel/parser/lib/index.js:11127:23)
    at FlowParserMixin.parseMaybeUnaryOrPrivate (/app.asar/node_modules/@babel/parser/lib/index.js:10956:61)
    at FlowParserMixin.parseExprOps (/app.asar/node_modules/@babel/parser/lib/index.js:10962:23)
    at FlowParserMixin.parseMaybeConditional (/app.asar/node_modules/@babel/parser/lib/index.js:10937:23)
    at FlowParserMixin.parseMaybeAssign (/app.asar/node_modules/@babel/parser/lib/index.js:10895:21)
    at FlowParserMixin.parseMaybeAssign (/app.asar/node_modules/@babel/parser/lib/index.js:6030:18)
    at FlowParserMixin.parseExpressionBase (/app.asar/node_modules/@babel/parser/lib/index.js:10845:23)
    at /app.asar/node_modules/@babel/parser/lib/index.js:10840:39
    at FlowParserMixin.allowInAnd (/app.asar/node_modules/@babel/parser/lib/index.js:12635:16)
    at FlowParserMixin.parseExpression (/app.asar/node_modules/@babel/parser/lib/index.js:10840:17)
    at FlowParserMixin.parseStatementContent (/app.asar/node_modules/@babel/parser/lib/index.js:13043:23)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:12917:17)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:5309:24)
    at FlowParserMixin.parseBlockOrModuleBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13497:25)
    at FlowParserMixin.parseBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13489:10)
    at FlowParserMixin.parseBlock (/app.asar/node_modules/@babel/parser/lib/index.js:13477:10)
    at FlowParserMixin.parseFunctionBody (/app.asar/node_modules/@babel/parser/lib/index.js:12287:24)
    at FlowParserMixin.parseFunctionBody (/app.asar/node_modules/@babel/parser/lib/index.js:5284:18)
    at FlowParserMixin.parseFunctionBodyAndFinish (/app.asar/node_modules/@babel/parser/lib/index.js:12271:10)
    at FlowParserMixin.parseFunctionBodyAndFinish (/app.asar/node_modules/@babel/parser/lib/index.js:5293:18)
    at FlowParserMixin.parseMethod (/app.asar/node_modules/@babel/parser/lib/index.js:12226:31)
    at FlowParserMixin.parseObjectMethod (/app.asar/node_modules/@babel/parser/lib/index.js:12120:19)
    at FlowParserMixin.parseObjPropValue (/app.asar/node_modules/@babel/parser/lib/index.js:12154:23)
    at FlowParserMixin.parseObjPropValue (/app.asar/node_modules/@babel/parser/lib/index.js:5774:26)
    at FlowParserMixin.parsePropertyDefinition (/app.asar/node_modules/@babel/parser/lib/index.js:12083:17)
    at FlowParserMixin.parseObjectLike (/app.asar/node_modules/@babel/parser/lib/index.js:11993:21)
    at FlowParserMixin.parseExprAtom (/app.asar/node_modules/@babel/parser/lib/index.js:11464:23)
    at FlowParserMixin.parseExprAtom (/app.asar/node_modules/@babel/parser/lib/index.js:7238:20)
    at FlowParserMixin.parseExprSubscripts (/app.asar/node_modules/@babel/parser/lib/index.js:11171:23)
    at FlowParserMixin.parseUpdate (/app.asar/node_modules/@babel/parser/lib/index.js:11153:21)
    at FlowParserMixin.parseMaybeUnary (/app.asar/node_modules/@babel/parser/lib/index.js:11127:23)
    at FlowParserMixin.parseMaybeUnaryOrPrivate (/app.asar/node_modules/@babel/parser/lib/index.js:10956:61)
    at FlowParserMixin.parseExprOps (/app.asar/node_modules/@babel/parser/lib/index.js:10962:23)
    at FlowParserMixin.parseMaybeConditional (/app.asar/node_modules/@babel/parser/lib/index.js:10937:23)
    at FlowParserMixin.parseMaybeAssign (/app.asar/node_modules/@babel/parser/lib/index.js:10895:21)
    at FlowParserMixin.parseMaybeAssign (/app.asar/node_modules/@babel/parser/lib/index.js:6030:18)
    at /app.asar/node_modules/@babel/parser/lib/index.js:10863:39
    at FlowParserMixin.allowInAnd (/app.asar/node_modules/@babel/parser/lib/index.js:12635:16)
    at FlowParserMixin.parseMaybeAssignAllowIn (/app.asar/node_modules/@babel/parser/lib/index.js:10863:17)
    at FlowParserMixin.parseExportDefaultExpression (/app.asar/node_modules/@babel/parser/lib/index.js:14171:22)
    at FlowParserMixin.parseExportDefaultExpression (/app.asar/node_modules/@babel/parser/lib/index.js:5359:18)
    at FlowParserMixin.parseExport (/app.asar/node_modules/@babel/parser/lib/index.js:14075:25)
    at FlowParserMixin.parseExport (/app.asar/node_modules/@babel/parser/lib/index.js:5493:24)
    at FlowParserMixin.parseStatementContent (/app.asar/node_modules/@babel/parser/lib/index.js:13020:27)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:12917:17)
    at FlowParserMixin.parseStatement (/app.asar/node_modules/@babel/parser/lib/index.js:5309:24)
    at FlowParserMixin.parseBlockOrModuleBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13497:25)
    at FlowParserMixin.parseBlockBody (/app.asar/node_modules/@babel/parser/lib/index.js:13489:10)
    at FlowParserMixin.parseProgram (/app.asar/node_modules/@babel/parser/lib/index.js:12832:10)
    at FlowParserMixin.parseTopLevel (/app.asar/node_modules/@babel/parser/lib/index.js:12822:25)
    at FlowParserMixin.parseTopLevel (/app.asar/node_modules/@babel/parser/lib/index.js:6174:28)
    at FlowParserMixin.parse (/app.asar/node_modules/@babel/parser/lib/index.js:14674:10)
    at parse (/app.asar/node_modules/@babel/parser/lib/index.js:14716:38)
    at parser (/app.asar/node_modules/@babel/core/lib/parser/index.js:52:34)
    at parser.next (<anonymous>)
    at normalizeFile (/app.asar/node_modules/@babel/core/lib/transformation/normalize-file.js:87:38)
    at normalizeFile.next (<anonymous>)
    at run (/app.asar/node_modules/@babel/core/lib/transformation/index.js:31:50)
    at run.next (<anonymous>)
    at Object.transform (/app.asar/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at evaluateSync (/app.asar/node_modules/gensync/index.js:251:28)
    at Object.sync (/app.asar/node_modules/gensync/index.js:89:14)
    at Object.exports.compile (/app.asar/src/babel.js:60:16)
    at Object.compile (/app.asar/src/package-transpilation-registry.js:66:27)
    at compileFileAtPath (/app.asar/src/compile-cache.js:106:31)
    at /app.asar/src/compile-cache.js:251:22)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at requireModule (/app.asar/src/module-utils.js:3:17)
    at Package.requireMainModule (/app.asar/src/package.js:912:27)
    at /app.asar/src/package.js:141:16
    at Package.measure (/app.asar/src/package.js:82:19)
    at Package.load (/app.asar/src/package.js:127:10)
    at PackageManager.loadAvailablePackage (/app.asar/src/package-manager.js:701:10)
    at PackageManager.loadPackage (/app.asar/src/package-manager.js:630:19)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:774:17)
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:426:25)
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:85:26)
    at triggerExitCallback (/app.asar/src/buffered-process.js:280:9)
    at /app.asar/src/buffered-process.js:301:9
    at /app.asar/src/buffered-process.js:169:7)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
```

### Commands

```
     -2:44.4.0 core:move-left (input.hidden-input)
     -2:44.1.0 core:move-right (input.hidden-input)
  2x -2:43.8.0 editor:newline (input.hidden-input)
  3x -2:13.8.0 core:move-down (input.hidden-input)
  2x -2:12.4.0 editor:newline (input.hidden-input)
  4x -1:48.4.0 core:backspace (input.hidden-input)
     -1:45.8.0 core:move-up (input.hidden-input)
  4x -1:45.7.0 core:move-left (input.hidden-input)
     -1:44.5.0 core:move-right (input.hidden-input)
     -1:43.9.0 core:backspace (input.hidden-input)
     -1:39.6.0 core:move-up (input.hidden-input)
  5x -1:38.9.0 core:move-right (input.hidden-input)
     -1:37.5.0 core:backspace (input.hidden-input)
  5x -1:33.5.0 core:move-down (input.hidden-input)
  2x -1:31.4.0 editor:newline (input.hidden-input)
  4x -0:29.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-import-cost 1.2.0 
autoclose-html 0.23.0 
autoclose-html-plus 0.27.2 
file-icons 2.1.47 
highlight-selected 0.17.0 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
pigments 0.40.6 
```

**Comment by siddharthkp** [comment]
Hi! 

I am no longer maintaining this project, I'd recommend forking it for Pulsar
